### ISSUE TITLE
Create packages collector 

### ISSUE THREAD

**Issue by Seth1u** [juev/prometheus_oracle#11]
@juev for exporter in case of add new query to check another metrics, we can create an collector for new test. 
I think it would be a good idea to separate the different tests in different collector so that we avoid overloading the main.go with all the tests

Best regards

**Comment by juev** [comment]
@Seth1u please, provide example.

**Comment by Seth1u** [comment]
Hello @juev 
I was too busy.

My example :
In your main source code: 
package main
import (

"github.com/shinhwagk/oracle_exporter/collector"

)

func init() {
	prometheus.MustRegister(version.NewCollector("oracle_exporter"))
}

func handler(w http.ResponseWriter, r *http.Request) {
	filters := r.URL.Query()["collect[]"]
	log.Debugln("collect query:", filters)

	nc, err := collector.NewOracleCollector(filters...)
	if err != nil {
		log.Warnln("Couldn't create", err)
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte(fmt.Sprintf("Couldn't create %s", err)))
		return
	}

	registry := prometheus.NewRegistry()
	err = registry.Register(nc)
	if err != nil {
		log.Errorln("Couldn't register collector:", err)
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(fmt.Sprintf("Couldn't register collector: %s", err)))
		return
	}

	gatherers := prometheus.Gatherers{prometheus.DefaultGatherer, registry}

	// Delegate http serving to Prometheus client library, which will call collector.Collect.
	h := promhttp.InstrumentMetricHandler(
		registry,
		promhttp.HandlerFor(gatherers,
			promhttp.HandlerOpts{
				ErrorLog:      log.NewErrorLogger(),
				ErrorHandling: promhttp.ContinueOnError,
			}),
	)
	h.ServeHTTP(w, r)
}

func main() {
	var (
		listenAddress = kingpin.Flag("web.listen-address", "Address on which to expose metrics and web interface.").Default(":9101").String()
		metricsPath   = kingpin.Flag("web.telemetry-path", "Path under which to expose metrics.").Default("/metrics").String()
	)

	log.AddFlags(kingpin.CommandLine)
	kingpin.Version(version.Print("oracle_exporter"))
	kingpin.HelpFlag.Short('h')
	kingpin.Parse()

	log.Infoln("Starting oracle_exporter", version.Info())
	log.Infoln("Build context", version.BuildContext())

	// This instance is only used to check collector creation and logging.
	nc, err := collector.NewOracleCollector()
	if err != nil {
		log.Fatalf("Couldn't create collector: %s", err)
	}
	log.Infof("Available collectors:")
	collectors := []string{}
	for n := range nc.Collectors {
		collectors = append(collectors, n)
	}
	sort.Strings(collectors)
	for _, n := range collectors {
		log.Infof(" - %s", n)
	}

	http.HandleFunc(*metricsPath, handler)
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(`<html>
			<head><title>Oracle Exporter</title></head>
			<body>
			<h1>Oracle Exporter</h1>
			<p><a href="` + *metricsPath + `">Metrics</a></p>
			</body>
			</html>`))
	})

	log.Infoln("Listening on", *listenAddress)
	err = http.ListenAndServe(*listenAddress, nil)
	if err != nil {
		log.Fatal(err)
	}
}


In your collectors folder : 

create file collector.go 

package collector

import (
	"database/sql"
	"fmt"
	"os"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/common/log"
)

const namespace = "oracle"

var (
	scrapeDurationDesc = createNewDesc("scrape", "collector_duration_seconds", "oracle_exporter: Duration of a collector scrape.", []string{"collector"}, nil)
	scrapeSuccessDesc  = createNewDesc("scrape", "collector_success", "oracle_exporter: Whether a collector succeeded.", []string{"collector"}, nil)
	oracleUpDesc       = createNewDesc("", "up", "oracle_exporter: Whether the Oracle server is up.", nil, nil)
)

var (
	factories = make(map[string]func() Collector)
)

// OracleCollector implements the prometheus.Collector interface.
type oracleCollector struct {
	Collectors map[string]Collector
}

func registerCollector(collector string, factory func() Collector) {
	factories[collector] = factory
}

// NewOracleCollector creates a new OracleCollector
func NewOracleCollector(filters ...string) (*oracleCollector, error) {
	f := make(map[string]bool)
	for _, filter := range filters {
		_, exist := factories[filter]
		if !exist {
			return nil, fmt.Errorf("missing collector: %s", filter)
		}
		f[filter] = true
	}

	collectors := make(map[string]Collector)
	for c, factory := range factories {
		if len(f) == 0 || f[c] {
			collectors[c] = factory()
		}
	}

	return &oracleCollector{collectors}, nil
}

// Describe implements the prometheus.Collector interface.
func (n oracleCollector) Describe(ch chan<- *prometheus.Desc) {
	ch <- scrapeDurationDesc
	ch <- scrapeSuccessDesc
	ch <- oracleUpDesc
}

// Collect implements the prometheus.Collector interface.
func (n oracleCollector) Collect(ch chan<- prometheus.Metric) {
	begin := time.Now()
	dsn := os.Getenv("DATA_SOURCE_NAME")
	db, err := sql.Open("goracle", dsn)
	if err != nil {
		log.Errorln("Error opening connection to database:", err)
		ch <- prometheus.MustNewConstMetric(oracleUpDesc, prometheus.GaugeValue, float64(0))
		return
	}
	defer db.Close()

	isUpRows, err := db.Query("SELECT * FROM dual")
	if err != nil {
		log.Errorln("Error pinging Pracle:", err)
		ch <- prometheus.MustNewConstMetric(oracleUpDesc, prometheus.GaugeValue, float64(0))
		return
	}
	isUpRows.Close()

	ch <- prometheus.MustNewConstMetric(oracleUpDesc, prometheus.GaugeValue, float64(1))
	ch <- prometheus.MustNewConstMetric(scrapeDurationDesc, prometheus.GaugeValue, time.Since(begin).Seconds(), "connection")

	for name, c := range n.Collectors {
		func(name string, c Collector) {
			execute(db, name, c, ch)
		}(name, c)
	}
}

func execute(db *sql.DB, name string, c Collector, ch chan<- prometheus.Metric) {
	begin := time.Now()
	err := c.Update(db, ch)
	duration := time.Since(begin)

	var success float64 = 1

	if err != nil {
		log.Errorf("ERROR: metric [%s] collector failed after %fs: %s", name, duration.Seconds(), err)
		success = 0
	} else {
		log.Debugf("OK: metric [%s] collector succeeded after %fs.", name, duration.Seconds())
	}

	ch <- prometheus.MustNewConstMetric(scrapeDurationDesc, prometheus.GaugeValue, duration.Seconds(), name)
	ch <- prometheus.MustNewConstMetric(scrapeSuccessDesc, prometheus.GaugeValue, success, name)
}

// Collector is the interface a collector has to implement.
type Collector interface {
	Update(db *sql.DB, ch chan<- prometheus.Metric) error
}

func createNewDesc(subsystem string, name string, help string, vls []string, cls prometheus.Labels) *prometheus.Desc {
	return prometheus.NewDesc(prometheus.BuildFQName(namespace, subsystem, name), help, vls, cls)
}


And for example to collet flash_recovery Area:

package collector

import (
	"database/sql"
    "strconv"
	"github.com/prometheus/client_golang/prometheus"
)

type FRA19cCollector struct {
	descs [3]*prometheus.Desc
}

func init() {
	registerCollector("FRA-19c", NewFRA19cCollector)

}

// New NewFRA19cCollector
func NewFRA19cCollector() Collector {
	descs := [3]*prometheus.Desc{
		createNewDesc(sFRASystemName, "percent_reclaimable", "Generic counter metric from v$flashrecoveryarea view in Oracle.", []string{"num"}, nil),
		createNewDesc(sFRASystemName, "percent_used", "Generic counter metric from v$flashrecoveryarea view in Oracle.", []string{"num"}, nil),
		createNewDesc(sFRASystemName, "file_number", "Generic counter metric from v$flashrecoveryarea view in Oracle.",[]string{"num"}, nil),
	}

	return &FRA19cCollector{descs}
}

func (c *FRA19cCollector) Update(db *sql.DB, ch chan<- prometheus.Metric) error {
	rows, err := db.Query(sFRA19cSQL)

	if err != nil {
		return err
	}
	defer rows.Close()

	counter := 1
	for rows.Next() {
         
		var percent_reclaimable, percent_used, file_number float64
		if err := rows.Scan(&percent_reclaimable, &percent_used, &file_number); err != nil {
			return err
		}

		s_counter := strconv.Itoa(counter)
		ch <- prometheus.MustNewConstMetric(c.descs[0], prometheus.CounterValue, percent_reclaimable, s_counter)
		ch <- prometheus.MustNewConstMetric(c.descs[1], prometheus.CounterValue, percent_used, s_counter)
		ch <- prometheus.MustNewConstMetric(c.descs[2], prometheus.CounterValue, file_number, s_counter)
        counter+=1
	}
	return nil
}

const (
	sFRASystemName = "fra"
	sFRA19cSQL     = `
	select PERCENT_SPACE_RECLAIMABLE, PERCENT_SPACE_USED, NUMBER_OF_FILES  from v$flash_recovery_area_usage`
)

/////////////////////

And if you want to add another query or test you can just add your query with name and create a new collector file 

Thanks
