### ISSUE TITLE
Redundancy exporter in labels

### ISSUE THREAD

**Issue by juev** [juev/prometheus_oracle#2]
For `db_metric` with `exporter` we have:

```
oracledb_exporter_db_metric{database="DB1",exporter="oracledb",name="name1",value="101598180.65"} 1.0159818065e+08
```

We dont need exporter on labels.

@maksim77 

@Juev А зачем в метках exporter? Итак будет понятно по instance. К тому же в примере они какие-то разные :-)
https://twitter.com/maksim77/status/1227303664060116992

**Comment by maksim77** [comment]
А в этом примере ещё более страшная ошибка. Нив коем случае(!!!) Value не может быть в label. Таким образом ты генеришь новый ряд в tadb для каждого замера.

**Comment by juev** [comment]
> А в этом примере ещё более страшная ошибка. Нив коем случае(!!!) Value не может быть в label. Таким образом ты генеришь новый ряд в tadb для каждого замера.

Ну не скажи, еще как может. Так получается, что экспортер используется в качестве получения бизнес-метрик, которые примерно в половине случаев содержат в себе строковые данные. А строковые данные не могут использоваться в проме в качестве значений. И именно поэтому их выносят в отдельный лейбл. В зависимости от получаемого значения (0 или 1) мы либо ничего не делаем, либо генерируем алерт с использованием текста из лейбла.

**Comment by maksim77** [comment]
@juev такие случаи бывают конечно. Но пробрасывать в общем случае value в label это означает для каждой метрики твоего экспортера генерить новый ряд. Я смотрю на твой пример выше и там обычный float.

**Comment by juev** [comment]
@maksim77 обычный флоат в том случае, если числовое значение можно сконвертировать в него, в противном случае это обычная строка.

Чтобы для числовых величин не генерировать новые ряды можно попробовать оставлять незаполненными лейбл value, в этом случае один и тот же ряд будет использоваться для всех числовых значений.

В случае же со строками, да, это будут новые ряды. Но и используются они иначе, их нельзя использовать для построения графиков или числового анализа. Используются только для алертов по сути.

Другого варианта пока не придумал.

**Comment by maksim77** [comment]
А почему не добавить ещё одно поле в yaml конфига? Ну вот у тебя есть список запросов где указаны интервал, сам запрос, его название. Так добавь туда type. У которого может быть например три варианта:

* `string` - тогда действительно value метка будет содержать результат. 
* `bool` - тогда 1/0 будут в самом значении метрики. 
* `float` - результат выполнения просто в значении.

Это может быть три разных типа метрик.

**Comment by juev** [comment]
Интересная мысль, надо будет подумать над этим, спасибо!

**Comment by juev** [comment]
Опубликовал версию 0.2.0, в которой реализованы дополнительные параметры запросов. В случае использования value (по умолчанию), используются только базовые лейблы, не создавая новых рядов. И только в случае string будет добавляться значение value в лейблы.
